stages:
- check
- build
- deploy

pre-commit:
  stage: check
  image: python:3
  before_script:
  - pip install pre-commit
  script:
  - TMP_MSG_FILE="$(mktemp)"
  - git log -1 --pretty=%B > "${TMP_MSG_FILE}"
  - pre-commit run --all-files --color=always --hook-stage commit &&
    pre-commit run --all-files --color=always --hook-stage commit-msg --commit-msg-filename "${TMP_MSG_FILE}" &&
    pre-commit run --all-files --color=always --hook-stage post-commit || {
      >&2 echo "pre-commit checks failed. Please consider installing pre-commit";
      >&2 echo "hooks in your local Git clone by running \`make git-hooks-install\`.";
      exit 1;
    }

build-linux-executable:
  stage: build
  image: centos:7
  before_script:
  - yum install -y epel-release
  - yum install -y python36-pip upx
  script:
  - python3 setup.py bdist_pyinstaller
  - PLATFORM=$(python3 -c 'import platform; print("{}_{}".format(platform.system(), platform.machine()).lower())');
    mv "dist/${CI_PROJECT_NAME}" "dist/${CI_PROJECT_NAME}_${PLATFORM}"
  artifacts:
    expire_in: 1 week
    paths:
    - dist/

build-macos-executable:
  stage: build
  image: macos:high-sierra-xcode-python3
  tags:
  - libvirt
  script:
  - python3 setup.py bdist_pyinstaller
  - PLATFORM=$(python3 -c 'import platform; print("{}_{}".format(platform.system(), platform.machine()).lower())');
    mv "dist/${CI_PROJECT_NAME}" "dist/${CI_PROJECT_NAME}_${PLATFORM}"
  artifacts:
    expire_in: 1 week
    paths:
    - dist/

deploy-to-github:
  stage: deploy
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/deploy
  variables:
    GIT_STRATEGY: none
  only:
  - master@imeyer/detect-direct-checkins
  - develop@imeyer/detect-direct-checkins
  - tags@imeyer/detect-direct-checkins
  script:
  - mkdir --mode=700 ~/.ssh/
  - (umask 0377 && echo "${GITHUB_DEPLOY_KEY}" > ~/.ssh/id_rsa
                && echo "github.com ${GITHUB_HOST_KEY}" >> ~/.ssh/known_hosts)
  - git clone --mirror "${CI_REPOSITORY_URL}" "${CI_PROJECT_NAME}_mirror"
  - cd "${CI_PROJECT_NAME}_mirror";
    git push --mirror "git@github.com:IngoMeyer441/${CI_PROJECT_NAME}.git";
    cd ..
